export const CITY_GEN_DATA=[
    {
        cityName: "Steamport",
        peepsMin: 75,
        peepsMax: 200,
        sizeX: 3,
        sizeY: 2,
        roughPosition: "random",
        building: "hq",
        defenseLevel: 1,
        cathouseLevel: 0,
        description: "Hometown of a great mind. (you!)"
    },
    {
        cityName: "The Gravetary",
        peepsMin: 1,
        peepsMax: 1,
        sizeX: 1,
        sizeY: 1,
        roughPosition: "random",
        building: "graveyard",
        defenseLevel: 5,
        cathouseLevel: 0,
        description: "."
    },
    {
        cityName: "Pennyville",
        peepsMin: 150,
        peepsMax: 400,
        sizeX: 4,
        sizeY: 5,
        roughPosition: "random",
        building: "bank",
        defenseLevel: 5,
        cathouseLevel: 0,
        description: "Led by a successful and wealthy hustler mayor. They say his left ear tickles when he is near money."
    },
    {
        cityName: "3",
        peepsMin: 150,
        peepsMax: 400,
        sizeX: 4,
        sizeY: 5,
        roughPosition: "random",
        building: "bison",
        defenseLevel: 5,
        cathouseLevel: 0,
        description: "."
    },
    {
        cityName: "4",
        peepsMin: 150,
        peepsMax: 400,
        sizeX: 4,
        sizeY: 5,
        roughPosition: "random",
        building: "skinshop",
        defenseLevel: 5,
        cathouseLevel: 0,
        description: "."
    },
    {
        cityName: "Snapschad",
        peepsMin: 150,
        peepsMax: 400,
        sizeX: 4,
        sizeY: 5,
        roughPosition: "random",
        building: "gallery",
        defenseLevel: 5,
        cathouseLevel: 0,
        description: "."
    },
    {
        cityName: "6",
        peepsMin: 150,
        peepsMax: 400,
        sizeX: 4,
        sizeY: 5,
        roughPosition: "random",
        building: "saloon",
        defenseLevel: 5,
        cathouseLevel: 0,
        description: "."
    },
    {
        cityName: "7",
        peepsMin: 150,
        peepsMax: 400,
        sizeX: 4,
        sizeY: 5,
        roughPosition: "random",
        building: "---",
        defenseLevel: 5,
        cathouseLevel: 0,
        description: "."
    },
    {
        cityName: "Bonegrass fields",
        peepsMin: 150,
        peepsMax: 400,
        sizeX: 4,
        sizeY: 5,
        roughPosition: "random",
        building: "rails",
        defenseLevel: 5,
        cathouseLevel: 0,
        description: "."
    },
    {
        cityName: "Positive hills",
        peepsMin: 150,
        peepsMax: 400,
        sizeX: 4,
        sizeY: 5,
        roughPosition: "random",
        building: "trains",
        defenseLevel: 5,
        cathouseLevel: 0,
        description: "."
    },
    {
        cityName: "Big Pews",
        peepsMin: 150,
        peepsMax: 400,
        sizeX: 4,
        sizeY: 5,
        roughPosition: "random",
        building: "gunshop",
        defenseLevel: 5,
        cathouseLevel: 0,
        description: "."
    },
    {
        cityName: "11",
        peepsMin: 150,
        peepsMax: 400,
        sizeX: 4,
        sizeY: 5,
        roughPosition: "random",
        building: "stable",
        defenseLevel: 5,
        cathouseLevel: 0,
        description: "."
    },
    {
        cityName: "12",
        peepsMin: 150,
        peepsMax: 400,
        sizeX: 4,
        sizeY: 5,
        roughPosition: "random",
        building: "---",
        defenseLevel: 5,
        cathouseLevel: 0,
        description: "."
    }
]