# Generated by Django 5.2.11 on 2026-02-28 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=1000)),
                ('relations', models.IntegerField(default=1)),
                ('areas_json', models.TextField(default='[]')),
                ('rails_json', models.TextField(default='[]')),
                ('stations_json', models.TextField(default='[]')),
                ('unlocked_cities_json', models.TextField(default='[]')),
                ('purchased_items_json', models.TextField(default='{}')),
                ('building_state_json', models.TextField(default='{}')),
                ('loan_amount', models.IntegerField(default=0)),
                ('loan_active', models.BooleanField(default=False)),
                ('loan_time_remaining', models.IntegerField(default=0)),
                ('bison_unlocked', models.BooleanField(default=False)),
                ('bison_profit', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
